# Generated by Django 3.1.2 on 2020-12-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_auto_20201118_1601'),
        ('Api', '0011_auto_20201118_2119'),
    ]

    operations = [
    ]
